#!/usr/bin/env python3
import argparse
import sys
import random
import logging

from ai_qe.exceptions import InvalidInput
from ai_qe.config import Config
from ai_qe import AIQE
from ai_qe.web_app import start_app


def parse_args():
    parser = argparse.ArgumentParser(
        description="AI-QE command line tool"
    )

    # Group for Test Case Generation
    gen_group = parser.add_argument_group("Test Case Generation Options")
    gen_group.add_argument(
        "--request", "-r", dest="request_str",
        help="Natural language request for cases generation",
        type=str,
    )
    gen_group.add_argument(
        "--template-yaml", "-t", dest="yaml_path",
        help="Path to the template yaml file for cases generation",
        type=str,
    )
    gen_group.add_argument(
        "--test-case", "-c", dest="test_cases",
        help="Path to test cases raw files",
        type=str, nargs='+',
    )
    gen_group.add_argument(
        "--case-number", "-n", dest="case_num",
        help="Random pick up request number test cases",
        type=int,
    )

    # Group for LLM Configuration
    server_group = parser.add_argument_group("LLM Configuration Options")
    server_group.add_argument(
        "--server-ip", "-s", dest="server_ip",
        help="ollama server IP address",
        type=str,
    )
    server_group.add_argument(
        "--server-port", "-p", dest="server_port",
        help="ollama server Port number",
        type=int,
    )
    server_group.add_argument(
        "--model", "-m", dest="model",
        help="LLM model name",
        type=str,
    )
    server_group.add_argument(
        "--use-vertex-ai", dest="use_vertex_ai",
        help="Use Vertex AI when use Gemini models",
        action='store_true',
    )

    # Other general options
    gen_group.add_argument(
        "--results-dir", "-d", dest="result_dir",
        help="Directory path which used to store result files",
        type=str,
        default="./results"
    )
    parser.add_argument(
        "--config-yaml", "-f", dest="config_yaml",
        help="Path to the config yaml file",
        type=str,
    )
    parser.add_argument(
        '--log-level', "-l", dest="log_level",
        default='WARNING',
        choices=['DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL'],
        help='Set the logging level (default: WARNING)'
    )
    parser.add_argument(
        "--web", "-w", dest="web",
        help="Run the web interface",
        action='store_true',
    )
    return parser.parse_args()


def main():
    args = parse_args()

    numeric_level = getattr(logging, args.log_level.upper(), None)
    if not isinstance(numeric_level, int):
        raise ValueError(f'Invalid log level: {args.log_level}')
    logging.basicConfig(level=numeric_level, format='%(asctime)s - %(levelname)s - %(message)s')

    if args.config_yaml:
        Config.load_from_yaml(args.config_yaml)
    Config.load_from_args(args)
    if args.web:
        start_app()
        sys.exit(0)

    aiqe_inst = AIQE()

    if args.request_str:
        try:
            info = aiqe_inst.extract_info(args.request_str)
        except InvalidInput as e:
            logging.error(f"Cannot extract information from {args.request_str}")
            raise
        print(f"Start generating test cases")
        cases, log = aiqe_inst.gen_test_cases(info["test item"], info["test feature"])
    elif args.yaml_path:
        print(f"Start generating test cases")
        cases, log = aiqe_inst.gen_test_cases(yaml_file=args.yaml_path)
    elif args.test_cases:
        cases = []
        for case_file in args.test_cases:
            with open(case_file, "r") as fp:
                cases.append(fp.read())
    else:
        print("ERROR: Need use --request, --template-yaml or --test-case to pass some data for case generation")
        sys.exit(1)

    if args.case_num:
        cases = random.sample(cases, args.case_num)

    for i, case in enumerate(cases):
        print(f"Start using AI run case {i+1}")
        history = aiqe_inst.run_test(case)
        history_file = f"{args.result_dir}/case-{i+1}.log"
        with open(history_file, "w+") as fp:
            fp.write(history)
        print(f"Store case {i+1} execution history in file {history_file}")

    print("Finished!")
    sys.exit(0)


if __name__ == "__main__":
    main()
