llm_server_ip: "0.0.0.0"
llm_server_port: 11434
model: "jacob-ebey/phi4-tools"
verbose: false
use_vertex_ai: false
test_item_modules:
  - "memory_doc"
  - "rng_doc"
  - "vm_basic_doc"
test_item_dir: "./test_items/"
